//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoWantsToBeAMillionare
{
    using System;
    using System.Collections.Generic;
    
    public partial class Levels
    {
        public int Id { get; set; }
        public string question { get; set; }
        public string aA { get; set; }
        public string aB { get; set; }
        public string aC { get; set; }
        public string aD { get; set; }
        public string correct { get; set; }
        public Nullable<short> number { get; set; }
        public Nullable<int> cash { get; set; }
        public string imgSrc { get; set; }

        public String fiftyJockerImgSource { get; set; }
        public String friendJockerImgSource { get; set; }
        public String publicJockerImgSource { get; set; }

        public Boolean fiftyJockerIsEnable { get; set; }
        public Boolean friendJockerIsEnable { get; set; }
        public Boolean publicJockerIsEnable { get; set; }
    }
}
